// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	twitter "github.com/equimper/twitter"
	mock "github.com/stretchr/testify/mock"
)

// TweetRepo is an autogenerated mock type for the TweetRepo type
type TweetRepo struct {
	mock.Mock
}

// All provides a mock function with given fields: ctx
func (_m *TweetRepo) All(ctx context.Context) ([]twitter.Tweet, error) {
	ret := _m.Called(ctx)

	var r0 []twitter.Tweet
	if rf, ok := ret.Get(0).(func(context.Context) []twitter.Tweet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitter.Tweet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, tweet
func (_m *TweetRepo) Create(ctx context.Context, tweet twitter.Tweet) (twitter.Tweet, error) {
	ret := _m.Called(ctx, tweet)

	var r0 twitter.Tweet
	if rf, ok := ret.Get(0).(func(context.Context, twitter.Tweet) twitter.Tweet); ok {
		r0 = rf(ctx, tweet)
	} else {
		r0 = ret.Get(0).(twitter.Tweet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, twitter.Tweet) error); ok {
		r1 = rf(ctx, tweet)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TweetRepo) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TweetRepo) GetByID(ctx context.Context, id string) (twitter.Tweet, error) {
	ret := _m.Called(ctx, id)

	var r0 twitter.Tweet
	if rf, ok := ret.Get(0).(func(context.Context, string) twitter.Tweet); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(twitter.Tweet)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
