// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	graph "github.com/equimper/twitter/graph"
	mock "github.com/stretchr/testify/mock"
)

// ResolverRoot is an autogenerated mock type for the ResolverRoot type
type ResolverRoot struct {
	mock.Mock
}

// Mutation provides a mock function with given fields:
func (_m *ResolverRoot) Mutation() graph.MutationResolver {
	ret := _m.Called()

	var r0 graph.MutationResolver
	if rf, ok := ret.Get(0).(func() graph.MutationResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.MutationResolver)
		}
	}

	return r0
}

// Query provides a mock function with given fields:
func (_m *ResolverRoot) Query() graph.QueryResolver {
	ret := _m.Called()

	var r0 graph.QueryResolver
	if rf, ok := ret.Get(0).(func() graph.QueryResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.QueryResolver)
		}
	}

	return r0
}

// Tweet provides a mock function with given fields:
func (_m *ResolverRoot) Tweet() graph.TweetResolver {
	ret := _m.Called()

	var r0 graph.TweetResolver
	if rf, ok := ret.Get(0).(func() graph.TweetResolver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.TweetResolver)
		}
	}

	return r0
}
